kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: nginx-web
  namespace: raccoon-army
spec:
  repo: https://github.com/team-raccoons/fleet-push-pattern.git
  branch: main
  paths:
  - fleet-clusters/nginx-web
  targets:
  - name: aws
    clusterSelector:
      matchLabels:
        env: aws

