kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: nginx-web-conf-us
  namespace: raccoon-army
spec:
  repo: https://github.com/team-raccoons/fleet-push-pattern.git
  branch: main
  revision: DEPLOY_TAG
  paths:
  - fleet-clusters/nginx-conf
  keepResources: true
  targets:
  - name: us
    clusterSelector:
      matchLabels:
        location: us

